### ISSUE TITLE
Compile error with current source (20230606)

### ISSUE THREAD

**Issue by mrgw454** [spotlessmind1975/ugbasic#609] opened 2023-06-06 13:56 UTC
Pulled latest source:

git pull
git submodule update --recursive

Started to compile for CoCo target and got the following error:

make target=coco clean compiler

make[1]: Entering directory '/home/ron/source/ugbasic/ugbc'
src/targets/common/_infrastructure.c: In function ‘variable_swap’:
src/targets/common/_infrastructure.c:2510:21: error: a label can only be part of a statement and a declaration is not a statement
 2510 |                     Variable * temp = variable_temporary( _environment, VT_FLOAT, "(temp)" );
      |                     ^~~~~~~~
In file included from src/targets/common/_infrastructure.c:35:
src/targets/common/_infrastructure.c: In function ‘variable_compare’:
src/targets/common/../../ugbc.h:2057:21: error: a label can only be part of a statement and a declaration is not a statement
 2057 | #define MAKE_LABEL  char label[12]; sprintf( label, "_label%d", UNIQUE_ID);
      |                     ^~~~
src/targets/common/_infrastructure.c:3312:29: note: in expansion of macro ‘MAKE_LABEL’
 3312 |                             MAKE_LABEL
      |                             ^~~~~~~~~~
src/targets/common/_infrastructure.c: In function ‘variable_less_than’:
src/targets/common/../../ugbc.h:2057:21: error: a label can only be part of a statement and a declaration is not a statement
 2057 | #define MAKE_LABEL  char label[12]; sprintf( label, "_label%d", UNIQUE_ID);
      |                     ^~~~
src/targets/common/_infrastructure.c:3861:29: note: in expansion of macro ‘MAKE_LABEL’
 3861 |                             MAKE_LABEL
      |                             ^~~~~~~~~~
src/targets/common/_infrastructure.c: In function ‘variable_greater_than’:
src/targets/common/../../ugbc.h:2057:21: error: a label can only be part of a statement and a declaration is not a statement
 2057 | #define MAKE_LABEL  char label[12]; sprintf( label, "_label%d", UNIQUE_ID);
      |                     ^~~~
src/targets/common/_infrastructure.c:4182:29: note: in expansion of macro ‘MAKE_LABEL’
 4182 |                             MAKE_LABEL
      |                             ^~~~~~~~~~
make[1]: *** [makefile:628: objs.coco/src/targets/common/_infrastructure.o] Error 1
make[1]: Leaving directory '/home/ron/source/ugbasic/ugbc'
make: *** [makefile:239: compiler] Error 2

Please assist and thank you!

**Comment by spotlessmind1975** [comment] 2023-06-06 20:57
Hello @mrgw454 , and **thank you for the bug report!**

The problem is related to the version of the compiler used. Unfortunately, I can only fix the bug reports you submitted here, since the source code compiles correctly with the version I usually use. Anyway, I've made the corrections - can you be so kind as to check if the problem goes away? So I close this bug. Thank you again!

**Comment by mrgw454** [comment] 2023-06-06 22:02
Just pulled and tried it again.

make[1]: Entering directory '/home/ron/source/ugbasic/ugbc'
In file included from src/targets/common/_infrastructure.c:35:
src/targets/common/_infrastructure.c: In function ‘variable_greater_than’:
src/targets/common/../../ugbc.h:2057:21: error: a label can only be part of a statement and a declaration is not a statement
 2057 | #define MAKE_LABEL  char label[12]; sprintf( label, "_label%d", UNIQUE_ID);
      |                     ^~~~
src/targets/common/_infrastructure.c:4185:29: note: in expansion of macro ‘MAKE_LABEL’
 4185 |                             MAKE_LABEL
      |                             ^~~~~~~~~~
make[1]: *** [makefile:628: objs.coco/src/targets/common/_infrastructure.o] Error 1
make[1]: Leaving directory '/home/ron/source/ugbasic/ugbc'
make: *** [makefile:239: compiler] Error 2

Looks like many of them were resolved.  

What compiler version are you using?  

Thank you for helping with this issue!

-Ron

**Comment by spotlessmind1975** [comment] 2023-06-06 22:54
Hi @mrgw454 , and thank you for your feedback!

I fixed this one, please try again.

The compiler version follows:

    $ gcc --version
    gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
    Copyright (C) 2021 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by mrgw454** [comment] 2023-06-06 22:59
It's working now.  I'm compiling on 2 different systems.  ARM (Raspberry Pi OS, latest version) which uses gcc 10.2.1 and an older Linux Mint x64 system using gcc 9.4.0.  I'm mainly concerned with keeping things working on the Raspberry Pi (if possible).

Thank you again for your speedy resolution!

**Comment by spotlessmind1975** [comment] 2023-06-07 12:16
Hi @mrgw454 , thank you for the very kind feedback, and for describing the version of your compilers. In next days I try to set up a build environment with those versions as well, to avoid such problems in the future. Thank you again, and happy retrocoding!

**Closed by spotlessmind1975** 2023-06-07 12:16 UTC
Labels: bug, coco
