### ISSUE TITLE
Load image crash after 3 loads COCO

### ISSUE THREAD

**Issue by ericomont** [spotlessmind1975/ugbasic#606] opened 2023-05-17 09:57 UTC
Adding the forth load image command crashes the output on the emulator. Those are 4 256x192 1bit images. They all load ok alone or up to 3. At that max the bin is at ~21kb, considering total 64kb, it should load more images before running out of memory (so memory bust can't be).

**Comment by spotlessmind1975** [comment] 2023-05-20 21:27
Hello @ericomont , first of all **thank you for your bug report!**

According to the reference technical documentation, which I used to integrate with the COCO 1 computer, the RAM memory available for the COCO 1 computers is actually up to 32 KB (yelllow color). We need to use at least a COCO 2 to have 64 KB (green color) but we need to make a bank switch (cyan color). I forward a copy of the explanation here, with the [direct link](https://www.lomont.org/software/misc/coco/Lomont_CoCoHardware.pdf):

![image](https://github.com/spotlessmind1975/ugbasic/assets/11718606/5f4345ac-edb7-4e4a-bba0-c1d1620f5177)

So, strictly speaking, this is not a "bug" but the expected behavior. Because you can't exceed a size of 32 KB of RAM on COCO 1. However, from empirical tests carried out on the XRoar emulator, the distinction between COCO 1 and COCO 2 would seem very blurred.

Indeed, by enabling the RAM bank, even if we have selected the `coco` machine (therefore: COCO 1), the bank switch would seem to take place -- and infact, after the change, from the `$8000` position we will find RAM and no longer the ROM. However, even though the emulator claims to have read all of the binary beyond location `$8000`, it would appear as if memory beyond `$8000` is not written from the file. 

At the moment I don't know what the reason is, and I'm investigating the behavior of the emulator. As soon as I can figure out how to load a binary of more than 22,016 bytes into XRoar, I'll try to distinguish between COCO 1 and COCO 2, and let ugBASIC use almost all of the 50 or so KB that will remain available.

**Comment by spotlessmind1975** [comment] 2023-05-20 23:49
Hello @ericomont, from a discussion with COCO computer experts, the following emerged. 

Unlike what is written in the technical documentation available as well as in the FAQs, there are no significant differences in the hardware of COCO 1 and COCO 2, except in the amount of starting RAM memory: 32 KB (can be increased to 64 KB) for the COCO 1, and 64KB for the COCO 2. Both share indexing and banking modes, which explains why the emulator treats them similarly. On the other hand, it would appear that the RAM memory is not accessible if the ROM memory is active. Unlike Commodore implementations, the switching is complete and thus inhibits writing (RAM does not remain available for writing). As a result, the emulator cannot load beyond address `$8000` because the ROM is active, which makes the memory "read only".

It is therefore necessary to implement an alternative method of reading the files, which should be able to load into the underlying RAM memory. Once this hurdle is cleared, the rest of the implementation should work fine.

**Comment by ericomont** [comment] 2023-05-21 16:30
Nice, I kind of have an idea the problem is related to the ALL RAM mode, and that rom must be repositioned because it sits at the end of the 4, 16 or 32k memory space, but I'm not hardware or asm savvy enough to actually understand the underlyings.
It is known that software from that time could overcome the "32k limit" so I'd guess it should be possible to work a solution.
Anyways, super thanks for the effort, I will try to help anyway I can.

**Comment by spotlessmind1975** [comment] 2023-05-22 18:42
Hello @ericomont , the problem has been solved and now all the RAM memory is available, without any limitation. The only thing to note is that the format that allows you to overcome this limit is no longer the "BIN" format (which maintains the 32 KB limit) but the "DSK" format that allows you to insert a loader written in a mix of BASIC and ASSEMBLY. The mechanism used does not copy the BASIC from the ROM to the RAM, which therefore remains at the complete disposal of the program. To load the program it is necessary to load and run the BASIC LOADER.BAS program.

The fix has been published with COLDFIX v1.13.3 [rev. 20230522.2020]

**Closed by spotlessmind1975** 2023-05-22 18:42 UTC
Labels: bug, coco
