### ISSUE TITLE
[6809] cpu_move_8bit_indirect_with_offset not found

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#219] opened 2021-11-14 17:11 UTC
I have got the following compilation error with fix #214:
```
$ time make target=mo5 output=k7 compiler -j4 && ugbc/exe/ugbc.mo5 -o tst.k7 tst.bas tst.asm
make[1]: Entering directory '/cygdrive/c/Users/Utilisateur/Desktop/Thomson/c6809-0.83/ugbasic/ugbc'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: objs.mo5/src/targets/common/get_cmove.o: in function `get_cmove':
/cygdrive/c/Users/Utilisateur/Desktop/Thomson/c6809-0.83/ugbasic/ugbc/src/targets/common/get_cmove.c:83: undefined reference to `cpu_move_8bit_indirect_with_offset'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Utilisateur/Desktop/Thomson/c6809-0.83/ugbasic/ugbc/src/targets/common/get_cmove.c:84: undefined reference to `cpu_move_8bit_indirect_with_offset'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: objs.mo5/src/targets/mo5/text_get_at.o: in function `get_at':
/cygdrive/c/Users/Utilisateur/Desktop/Thomson/c6809-0.83/ugbasic/ugbc/src/targets/mo5/text_get_at.c:71: undefined reference to `cpu_move_8bit_indirect_with_offset'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: /cygdrive/c/Users/Utilisateur/Desktop/Thomson/c6809-0.83/ugbasic/ugbc/src/targets/mo5/text_get_at.c:72: undefined reference to `cpu_move_8bit_indirect_with_offset'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: objs.mo5/src/targets/mo5/text_get_paper.o: in function `get_paper':
/cygdrive/c/Users/Utilisateur/Desktop/Thomson/c6809-0.83/ugbasic/ugbc/src/targets/mo5/text_get_paper.c:67: undefined reference to `cpu_move_8bit_indirect_with_offset'
/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: objs.mo5/src/targets/mo5/text_get_pen.o:/cygdrive/c/Users/Utilisateur/Desktop/Thomson/c6809-0.83/ugbasic/ugbc/src/targets/mo5/text_get_pen.c:66: more undefined references to `cpu_move_8bit_indirect_with_offset' follow
collect2: error: ld returned 1 exit status
make[1]: *** [makefile:323: compiler] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/Utilisateur/Desktop/Thomson/c6809-0.83/ugbasic/ugbc'
make: *** [makefile:128: compiler] Error 2

real    0m1.080s
user    0m0.277s
sys     0m0.822s

```

Apparently the symbol `cpu_move_8bit_indirect_with_offset` isn't defined.

and looking at: https://github.com/spotlessmind1975/ugbasic/blob/e1e4b6bc5d8c7e22df9da621d8bc2e03f8d3dffd/ugbc/src/hw/6809.h#L308 one cannot find any trace of such a symbol (as far as I can tell). Instead one can find `cpu_move_8bit_indirect_with_offset2` which is possibly a typo.

**Comment by Samuel-DEVULDER** [comment] 2021-11-14 17:43
If I add
`
#define cpu_move_8bit_indirect_with_offset( _environment, _source, _value, _offset ) cpu6809_move_8bit_with_offset( _environment, _source, _value, _offset )
`
in 6809.h, then the compilation succeed.

**Comment by spotlessmind1975** [comment] 2021-11-14 21:18
@Samuel-DEVULDER **It's a really weird thing**, because I had refactored that function on all processors. The fix you introduced is a great workaround. By tomorrow I will apply the actual fix, which consists in replacing the second with the first function.

**Comment by spotlessmind1975** [comment] 2021-11-14 21:20
Duplicate of #214

**Comment by spotlessmind1975** [comment] 2021-11-14 22:56
Fixed compilation.

**Closed by spotlessmind1975** 2021-11-14 22:56 UTC
Labels: bug, duplicate, 6809
