### ISSUE TITLE
Wrong HEX$ values under z80

### ISSUE THREAD

**Issue by teutoburgo** [spotlessmind1975/ugbasic#638] opened 2023-08-08 21:52 UTC
Hello,
trying to compile the code sample:
https://retroprogramming.iwashere.eu/ugbasic:user:example:maths_example_07
for zx spectrum. Failing to execute the output .tap file, Speccy freezes.
Any advice?
Thanks.

**Comment by spotlessmind1975** [comment] 2023-08-09 22:46
Hi @teutoburgo and **thank you for your kind bug report!**

![image](https://github.com/spotlessmind1975/ugbasic/assets/11718606/c84a3ae5-e462-4407-8540-2f1e10c5b839)

The example compiles without problems, both with the `main` version and with the `beta` version, using current IDE. If anything, there's a problem because it doesn't seem like the output is as expected. The problem is not limited to the `zx` but affects all targets using the `z80` as a processor. I therefore follow up on this report as a "bug", and I'll let you know when it's fixed.

**Comment by teutoburgo** [comment] 2023-08-09 23:25
> Hi @teutoburgo and **thank you for your kind bug report!**
> 

You're welcome!
Congrats for your nice work! :)

**Comment by spotlessmind1975** [comment] 2023-08-10 11:20
Hi @teutoburgo , the issue has been fixed on COLDFIX v1.14.1 [rev. 20230810.1318],

**Closed by spotlessmind1975** 2023-08-10 11:20 UTC
Labels: bug, z80
